SportRentals/Controllers/ProductUserController.cs
using SportRentals.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportRentals.Models;
using SportRentals.ViewModels;
using System.Web.Security;
using Microsoft.AspNet.Identity;

namespace SportRentals.Controllers
{
    public class ProductUserController : Controller
    {
        private ProductRepository productRepository = new Repository.ProductRepository();
        private ShopRepository shopRepository = new ShopRepository();
        private CategoryRepository categoryRepository = new CategoryRepository();


       
        public ActionResult Index()
        {
            var shopViewModel = new ProductCategoryShopViewModel();

            var shops = shopRepository.GetAllShops();
            shops.Add(new ShopModel() { Name = "- All -", ShopId = 0 });

            var orderedShops = shops.OrderBy(x => x.Name);
            SelectList shopList = new SelectList(orderedShops, "ShopID", "Name");
            ViewData["ShopList"] = shopList;

            var shop = orderedShops.FirstOrDefault();



            if (Session["startDate"] != null && Session["endDate"] != null)
            {
                shopViewModel.StartDate = (DateTime)Session["startDate"];
                shopViewModel.EndDate = (DateTime)Session["endDate"];
            }
            else
            {
                shopViewModel.StartDate = DateTime.Today;
                shopViewModel.EndDate = DateTime.Today;
            }


            if (Session["shopId"] != null)
            {
                shopViewModel.ShopID = (int)Session["shopId"];
            }
            else
            {
                shopViewModel.ShopID = 0;
            }


            if (Session["products"] != null)
            {
                shopViewModel.Products = (List<ProductModel>)Session["products"];
            }
            else
            {
                shopViewModel.Products = productRepository.GetAllProducts();
            }


            return View("IndexUser", shopViewModel);
        }


        [HttpPost]
        public ActionResult Search(FormCollection collection)
        {
            var shopViewModel = new ProductCategoryShopViewModel();
            TryUpdateModel(shopViewModel);

            var shops = shopRepository.GetAllShops();
            shops.Add(new ShopModel() { Name = "- All -", ShopId = 0 });

            var orderedShops = shops.OrderBy(x => x.Name);
            SelectList shopList = new SelectList(orderedShops, "ShopID", "Name");
            ViewData["ShopList"] = shopList;

            var shop = shops.FirstOrDefault(x => x.ShopId == shopViewModel.ShopID);

            if (shopViewModel.ShopID == 0)
            {
                shopViewModel.Products = productRepository.GetAllProducts();
            }
            else
            {
                shopViewModel.Products = productRepository.GetAllProductsByCategoryID(shop.CategoryID);
            }

            Session["startDate"] = shopViewModel.StartDate;
            Session["endDate"] = shopViewModel.EndDate;
            Session["shopId"] = shopViewModel.ShopID;
            Session["Products"] = shopViewModel.Products;
            Session["shopId"] = shopViewModel.ShopID;

            return View("IndexUser", shopViewModel);

        }


        public ActionResult AddToCart(int ID)
        {
            Cart shoppingcart = Session["cart"] as Cart;

            if(shoppingcart == null)
            {
                shoppingcart = new Cart();
            }

            shoppingcart.AddProduct(ID);

            Session["cart"] = shoppingcart;
            Session["numberofitems"] = shoppingcart.NumberofItems();
            
            TempData["ProductAdded"] = true;
            //return Json(new { items = shoppingcart.NumberofItems(), message = "Your product has been added!" }, JsonRequestBehavior.AllowGet);
            



            return RedirectToAction("Index");
        }

        // GET: ProductUser/Details/5
        public ActionResult Details(int id)
        {
            Models.ProductModel productModel = productRepository.GetProductById(id);
            return View("Details", productModel);
        }

    
        [HttpPost]
        public ActionResult Checkout(FormCollection collection)
        {
            var shopViewModel = new ProductCategoryShopViewModel();
            TryUpdateModel(shopViewModel);

            return RedirectToAction("ViewCart", "Cart");
        }
    }
}

SportRentals/Views/ProductUser/Details.cshtml
@model SportRentals.Models.ProductModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>

<body>

    <div class="container">
        <h2>Modal Example</h2>
        <!-- Button to Open the Modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
            Open modal
        </button>

        <!-- The Modal -->
        <div class="modal" id="myModal">
            <div class="modal-dialog">
                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Modal Heading</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        Modal body..
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>

                </div>
            </div>
        </div>

    </div>
</body>
</html>

SportRentals/Views/ProductUser/IndexUser.cshtml
@model SportRentals.ViewModels.ProductCategoryShopViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //Layout = "~/Views/Shared/_assemblylayout.cshtml";
}



@section Scripts {
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

}


@using (Html.BeginForm("Search", "ProductUser"))
{
    @Html.AntiForgeryToken()
    <div class="flex-container-menu">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="input-group mb-4">
            <div class="input-group-prepend">
                @Html.LabelFor(model => model.ShopID, htmlAttributes: new { @class = "input-group-text" })
            </div>
            <div style="width: 74%">
                @Html.DropDownListFor(model => model.ShopID, ViewData["ShopList"] as IEnumerable<SelectListItem>, new { @class = "custom-select" })
                @Html.HiddenFor(model => model.ShopID)
            </div>
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="input-group mb-4">
                <div class="input-group-prepend">
                    @Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "input-group-text" })
                </div>
                <div style="width: 64%">
                    @Html.DropDownListFor(model => model.CategoryID, ViewData["CategoryList"] as IEnumerable<SelectListItem>, new { @class = "custom-select" })
                </div>

            </div>*@
        <div class="input-group mb-4">
            <div class="input-group-prepend">
                <span>
                    @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "input-group-text" })
                </span>
            </div>
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            <div style="width: 61%">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datetimepickerstart" } })
            </div>
        </div>
        <div class="input-group mb-4">
            <div class="input-group-prepend">
                <span>
                    @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "input-group-text" })
                </span>
            </div>
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            <div style="width: 61%">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datetimepickerend" } })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-9">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>

    </div>

}

@using (Html.BeginForm("Checkout", "ProductUser"))
{

    <div class="flex">


        @foreach (var item in Model.Products)
        {

        <section>
            <img src="@item.ImageUrl" alt="Smartphone" />
            <h5>@Html.DisplayFor(modelItem => item.Name)</h5>
            <ul>
                <li>Price: @Html.DisplayFor(modelItem => item.DailyPrice)</li>
            </ul>
            <div  style="margin-bottom: 15px;">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal_@item.ProductID">
                    Details
                </button>
                @Html.ActionLink("Buy Now", "AddToCart", new { id = item.ProductID }, new { @class = "btn btn-danger" })
            </div>
            <div class="container">


                <div class="modal" id="modal_@item.ProductID">
                    <div class="modal-dialog">
                        <div class="modal-content">


                            <div class="modal-header">
                                <h4 class="modal-title">Product Details</h4>
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </div>

                            <div class="modal-body" style="padding:20px 20px;">
                                <div class="img-rounded">
                                    @Html.DisplayFor(modelItem => item.Description)
                                    <br /><br />
                                    <h6>Stock: <b>@Html.DisplayFor(modelItem => item.Stock)</b></h6>
                                </div>
     
                            </div>


                            <!-- Modal footer -->
                            <div class="modal-footer">
                                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </section>






        }
    </div>


    <div class="form-group" align ="right">
            <input type="submit" value="Proceed to checkout" class="btn btn-default" />
    </div>
}
<script type="text/javascript">
    $(function () {
        $('.datetimepickerend').datepicker({
            uiLibrary: 'bootstrap4'
        });
    });
    $(function () {
        $('.datetimepickerstart').datepicker({
            uiLibrary: 'bootstrap4'
        });
    });

</script>
@if (TempData["ProductAdded"] != null)
{
    <div class="modal" id="dialog">
        <div class="modal-dialog">
            <div class="modal-content" style="width: 320px;">
                <div class="modal-header">
                    <h4 class="modal-title">Shopping Cart</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <div class="modal-body">
                    <div class="img-rounded">
                        Your product has been added!
                    </div>
                    <div align="right">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script>
        $(function () {
            $("#dialog").modal();
        });
    </script>
}